kb = struct('LevelOneLeafOne', "Is it a summer trip?", ...
            'LevelTwoLeafOne', "Would you like to travel to the seaside?", ...
            'LevelTwoLeafTwo', "Would you like to have a ski trip?", ...
            'LevelThreeLeafOne', "Would you prefer a sandy beach?", ...
            'LevelThreeLeafTwo', "Would you like to have a lake trip?", ...
            'LevelThreeLeafThree', "Would you like to have a mountain trip?", ...
            'LevelThreeLeafFour', "Would you like to travel on Christmas vacations?", ...
            'LevelFourLeafOne', "Would you prefer a yellow sand?", ...
            'LevelFourLeafTwo', "Would you prefer a black shingle?", ...
            'LevelFourLeafThree', "Would you like to have a fishing trip?", ...
            'LevelFourLeafFour', "Would you like to have a forest trip?", ...
            'LevelFourLeafFive', "Would you like to have a fake snow on mountains?", ...
            'LevelFourLeafSix', "Would you prefare a skating run to be included?", ...
            'LevelFourLeafSeven', "Would you like to have Christmas on the 25th of December?", ...
            'LevelFourLeafEight', "Would you like to see ice sculptures?", ...
            'LevelFiveLeafOne', "Would you like to have seashells on a beach?", ...
            'LevelFiveLeafTwo', "Would you prefer a black sand?", ...
            'LevelFiveLeafThree', "Would you prefer to have a lounger?", ...
            'LevelFiveLeafFour', "Would you prefer a multicolor shingle?", ...
            'LevelFiveLeafFive', "Would you like a boat to be included?", ...
            'LevelFiveLeafSix', "Would you like to have a diving trip?", ...
            'LevelFiveLeafSeven', "Would you like to gather both mushrooms and berries?", ...
            'LevelFiveLeafEight', "Would you like to drive an ATV?", ...
            'LevelFiveLeafNine', "Would you like a snowboarding to be included?", ...
            'LevelFiveLeafTen', "Would you like to have a natural cover?", ...
            'LevelFiveLeafEleven', "Would you like to combine both a skating ring and a ski track?", ...
            'LevelFiveLeafTwelve', "Would you like to have several ski tracks?", ...
            'LevelFiveLeafThirteen', "Would you like to take part in a Christmas fair?", ...
            'LevelFiveLeafFourteen', "Would you  like to have a traditional meal?", ...
            'LevelFiveLeafFifteen', "Would you like to take part in a sculpture creation?", ...
            'LevelFiveLeafSixteen', "Would you like to drive a scooter?", ...
            'LevelSixLeafOne', "Cyprus", ...
            'LevelSixLeafTwo', "Malta", ...
            'LevelSixLeafThree', "Island", ...
            'LevelSixLeafFour', "Hawaii", ...
            'LevelSixLeafFive', "Bali", ...
            'LevelSixLeafSix', "Turkey", ...
            'LevelSixLeafSeven', "Spain", ...
            'LevelSixLeafEight', "Greece", ...
            'LevelSixLeafNine', "USA", ...
            'LevelSixLeafTen', "Sweden", ...
            'LevelSixLeafEleven', "Indonesia", ...
            'LevelSixLeafTwelve', "Belarus", ...
            'LevelSixLeafThirteen', "Poland", ...
            'LevelSixLeafFourteen', "Brazil", ...
            'LevelSixLeafFifteen', "UAE", ...
            'LevelSixLeafSixteen', "Africa", ...
            'LevelSixLeafSeventeen', "Italy", ...
            'LevelSixLeafEighteen', "France", ...
            'LevelSixLeafNineteen', "Slovenia", ...
            'LevelSixLeafTwenty', "Austria", ...
            'LevelSixLeafTwentyOne', "Norway", ...
            'LevelSixLeafTwentyTwo', "Bulgaria", ...
            'LevelSixLeafTwentyThree', "Finland", ...
            'LevelSixLeafTwentyFour', "Switzerland", ...
            'LevelSixLeafTwentyFive', "Germany", ...
            'LevelSixLeafTwentySix', "Britain", ...
            'LevelSixLeafTwentySeven', "Russia", ...
            'LevelSixLeafTwentyEight', "Kazakhstan", ...
            'LevelSixLeafTwentyNine', "Mongolia", ...
            'LevelSixLeafThirty', "Japan", ...
            'LevelSixLeafThirtyOne', "Canada", ...
            'LevelSixLeafThirtyTwo', "Ukrain");

sizeMatr = 63;

matr = fillTable(sizeMatr);

disp(matr);

fns = fieldnames(kb);
ind = 1;
flag = 0;
found = 1;
while true    
%     if (flag == 1)
%         break;
%     end
    
    found = 0;
    res = MenuDialog(kb.(fns{ind})); 
    if (res == 1)
        tmpIndex = find(matr(ind, :) == 'y', 1);          
    else        
        tmpIndex = find(matr(ind, :) == 'n', 1);
    end    
    
    tmp = find(matr(:, tmpIndex) == 'y');
%     [m, n] = size(tmp);
    for i = 1:length(tmp)
        if (tmp(i) > ind)
            ind = tmp(i);
            found = 1;
            break;
        end
    end  
    
    if (found == 0)
        break;
    end
    
    
    
%     if (ind == tmp(length(tmp)))
%         flag = 1;
%     end;
    
%     ind = find(tmp, tmp > ind, 1);
   %ind = ind(1);
end

ind = find(matr(:, tmpIndex) == 'v', 1);
MessageBox(kb.(fns{ind}));

function matr = fillTable(sizeMatr)
    leafs = fix(sizeMatr / 2) + 1;
    rowNumber = sizeMatr;
    columnNumber = leafs;
    matr = repmat('-', rowNumber, columnNumber);
    
    vectSize = columnNumber;
    rowIndex = 1;
    while (vectSize >= 2)
        vect1 = repmat('y', vectSize / 2);
        vect2 = repmat('n', vectSize / 2);
        vect = [vect1; vect2];        
        
        for j = 1:vectSize:columnNumber            
            ind = 1;
            for i=j:j + vectSize - 1
                matr(rowIndex, i) = vect(ind); 
                ind = ind + 1;
            end            
            rowIndex = rowIndex + 1;           
        end
        
        vectSize = vectSize / 2;
    end
    
    ind = 1;
    for i=rowIndex:rowNumber
       matr(i, ind) = "v";
       ind = ind + 1;
    end
end


function result = MenuDialog(text)
    result = menu(text, 'Yes', 'No');
end

function MessageBox(text)
    msgbox({'Your contry is... ' text}, 'Result');
end